<?php

/*function mi_modulo_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
	ksm($form_state);
}*/

function mi_modulo_preprocess_field(&$variables, $hook){
	
	if ($variables['element']['#field_name'] == 'field_json_valores') {

		$v = $variables['element']['#items']->getValue()[0]['value'];
		$v = "<script>{$v}</script>";

		$variables['element']['#items']->setValue($v);

		ksm($variables['element']['#items']->getValue());
	}
}